#!/bin/bash

#SBATCH --time=60:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=10G

## Call cellranger count
## arg1 = Sample name (from sample sheet)
## arg2 = Organism
## arg3 = Fastq directory
## arg4 = Additional options (optional)

module purge
module load cellranger${CELLRANGER_VERSION}

SMP=$1
REF=$2
OUT=$3
shift; shift; shift

cellranger count \
  --id=$SMP \
  --sample=$SMP \
  --transcriptome=$REF \
  --fastqs=$OUT \
  --create-bam=false \
  --localcores=${SLURM_CPUS_PER_TASK} \
  --disable-ui $*
