#!/bin/bash

#SBATCH --time=30:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=24
#SBATCH --mem-per-cpu=4G

## Convert BCL files to fastq. Assumes Illumina run dir is current directory.
## Arg1 = Run ID
## Arg2 = Sample sheet
## Arg3 = Run directory
## Arg4 = Bases mask (optional, default=Y28N*,I8,I91N*)
##
## Example sample sheet:
##
## L,PBMC_1,SI-GA-A1
## L,PBMC_2,SI-GA-B1
## L,PBMC_3,SI-GA-C1
##
## where L is either a lane number or '*'.

RUNID=$1
SSHEET=$2
RUNDIR=$3

module purge
module load cellranger${CELLRANGER_VERSION}

# Detect if kit is single or dual
key=$(grep SI- $SSHEET | head -1 | cut -d , -f 3 )
case $key in
    SI-TT-*|SI-NT-*|SI-NN-*)
	kit="dual"
	;;
    SI-GA-*)
	kit="single"
	;;
esac

# Detect the kind of samplesheet we're using
sshdr=$(head -1 $SSHEET)
if [[ "$sshdr" == "Lane,Sample,Index" ]];
then
  ssheet="--csv=$SSHEET"
else
  ssheet="--samplesheet=$SSHEET"
fi

if [[ -z "$4" ]];
then
  if [[ "$kit" == "single" ]];
  then
    BM="Y28N*,I8N*,N*,Y91N*"
  else
    BM="Y28N*,I10,I10,Y91N*"
  fi
else
  BM=$4
fi

cellranger mkfastq --run="$RUNDIR" $ssheet \
  --id=$RUNID \
  --localcores=24 \
  --localmem=24 \
  --disable-ui \
  --use-bases-mask=$BM \
  --filter-single-index 
#  --ignore-dual-index \
