#!/bin/bash

#SBATCH --time=60:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=5G

## Call cellranger count for cytassist/HD
## arg1 = Parameters file
## arg2 = Sample name (from sample sheet)
## arg3 = Microscopy image file
## arg4 = CytAssist slide image file
## arg5 = Slide ID (or "-" if unknown)
## arg6 = Slide area
## arg8... = additional arguments to spaceranger count

module purge
module load spaceranger
#SPACERANGER=/blue/icbrbi/apps/spaceranger-3.0.1/bin/spaceranger
SPACERANGER=spaceranger

# Check if $2 is the name of builtin genome reference.
# If it's not, use $2 as-is (could be path to a custom ref)

PARAMS=$1
SMP=$2
IMG=$3
CYTAIMG=$4
SLIDE=$5
AREA=$6
shift 6
OTHERARGS=$*

source $PARAMS
REF=$GENOME

if [[ -d $REF ]];
then
  refdir=$REF
else
  refdir=$HPC_CELLRANGER_REF/$REF
fi

slideinfo=(${SLIDE//:/ })	# convert slide info to array
slidename=${slideinfo[0]}
slidefile=${slideinfo[1]}

if [[ ! -z $slidefile ]];
then
  sf="--slidefile $slidefile"
else
  sf=""
fi

case $slidename in
    V4*)
	imgarg=cytaimage
	;;
    *)
	imgarg=image
	;;
esac

if [[ -v PANEL ]];
then
    probeset="--probe-set $PANEL"
fi

#if [ "$4" == "" ];
#then
#  CHEM=""
#else
#  CHEM="-c $4"
#fi

if [[ "$MODE" == "cytassist" ]];
then
    $SPACERANGER count --id=$SMP --transcriptome=$refdir --libraries=$FASTQS \
		--image=$IMG --cytaimage=$CYTAIMG \
		--feature-ref $FEATURES \
		--slide $slidename $sf --area $AREA $probeset \
		--localcores=16 --disable-ui $OTHERARGS
else
    $SPACERANGER count --id=$SMP --transcriptome=$refdir --fastqs=$FASTQS \
		--image=$IMG --cytaimage=$CYTAIMG \
		--slide $slidename $sf --area $AREA $probeset \
		--create-bam false \
		--localcores=16 --disable-ui $OTHERARGS
fi
